[package]
name = "bfa"
version = "0.1.0"
edition = "2021"

[dependencies]
syscalls = "0.6.15"
libc = "0.2"

[dev-dependencies]
pretty_assertions = "1.4.0" # For nicer test output

[[bin]]
name = "syscall_test"
path = "src/syscall_test.rs"
